spring:
  application:
    name: eurekaserver
---
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/
#---
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/