server:
  port: 7674
spring:
  application:
    name: fegin-client
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

eureka:
  client:
     serviceUrl:
          defaultZone: http://eureka2:8762/eureka/,http://eureka1:8761/eureka/